### ISSUE TITLE
Add Git actions for Codecov

### ISSUE THREAD

**Issue by Shaunak01** [causify-ai/helpers#487]
We want to integrate Codecov to track and display coverage for our test suite. This will help us keep track of code quality and maintain a healthy testing culture. Below is the plan:

Steps and info for activating CodeCov: https://app.codecov.io/github/causify-ai/helpers/new

Steps:
- [x] Add codecove_requirements.txt and run pytest coverage action

Requirements              
```
coverage
codecov
```
In a GitHub Action, run tests and generate a coverage report:
```
pytest --cov --cov-branch --cov-report=xml
```

- [x] Select an upload token to add as a secret on GitHub
- [x] Add Codecov to GitHub Actions workflow yaml file
```
- name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v5
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
```

@samarth9008 @dremdem as you are working in restructuring our git actions can you guide as to where we should add codecov actions? The token is already added to `helpers` so we just have to add the actions.

This is just for test purposes, we have not bought this service yet. I will document this once tested or we solidify the plan.

FYI @gpsaggese pls guide if you can as well.
