### ISSUE TITLE
Docker fails due to missing Docker socket

### ISSUE THREAD

**Issue by aangelo9** [causify-ai/helpers#578]
When trying to run invoke commands, i ran into:
```
# invoke print_env
12:02:00 - INFO  hdbg.py init_logger:1018                               > cmd='/venv/bin/invoke print_env'
12:02:00 - WARN  hserver.py _raise_invalid_host:777                     Don't recognize host: host_os_name=Linux, am_host_os_name=None
[sudo] password for ubuntu: 
sudo: a password is required
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Run 'docker run --help' for more information
[sudo] password for ubuntu: 
sudo: a password is required
Traceback (most recent call last):
  File "/venv/bin/invoke", line 8, in <module>
    sys.exit(program.run())
             ^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/invoke/program.py", line 398, in run
    self.execute()
  File "/venv/lib/python3.12/site-packages/invoke/program.py", line 583, in execute
    executor.execute(*self.tasks)
  File "/venv/lib/python3.12/site-packages/invoke/executor.py", line 140, in execute
    result = call.task(*args, **call.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/invoke/tasks.py", line 138, in __call__
    result = self.body(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/helpers/lib_tasks_print.py", line 92, in print_env
    henv.env_to_str(
  File "/app/helpers/henv.py", line 543, in env_to_str
    msg += get_system_signature()[0] + "\n"
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/helpers/henv.py", line 505, in get_system_signature
    txt_tmp = hserver.get_docker_info()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/helpers/hserver.py", line 683, in get_docker_info
    docker_needs_sudo_ = docker_needs_sudo()
                         ^^^^^^^^^^^^^^^^^^^
  File "/app/helpers/hserver.py", line 631, in docker_needs_sudo
    assert False, "Failed to run docker"
           ^^^^^
AssertionError: Failed to run docker
```

This happened after [commit b36a90c](https://github.com/causify-ai/helpers/commit/b36a90cc360c135ea2b16df85d50a8b94d60ee2c) on masters. 

In `helpers/hserver.py`, docker_needs_sudo enforces that sudo is required.
```
# Taken from `helpers/hserver.py`
def docker_needs_sudo() -> bool:
    """
    Return whether Docker commands need to be run with sudo.
    """
    if not has_docker():
        return False
    # Another way to check is to see if your user is in the docker group:
    # > groups | grep docker
    rc = os.system("docker run hello-world 2>&1 >/dev/null")
    if rc == 0:
        return False
    #
    rc = os.system("sudo docker run hello-world 2>&1 >/dev/null")
    if rc == 0:
        return True
    assert False, "Failed to run docker"
```

Previously, when `[sudo] password for ubuntu: ` is prompted, we could skip it with ctrl+c, and continue on. But with the new logic, sudo is a must or it raises an assertion early.

FYI: @sonniki @gpsaggese

**Comment by sonniki** [comment]
Good decision to file an issue @aangelo9 . We need to bypass this check for people not working on the server by inserting `hserver.is_external_dev()` somewhere, probably upstream from this function. @aangelo9 can you investigate a bit and make a proposal (in a PR) where would be the most fitting place to put it?

**Comment by aangelo9** [comment]
Understood. I will draft a PR.

**Comment by gpsaggese** [comment]
I've been rewriting all that logic and I can't test on all the external devices.

IIUC, my take is that either one can run `docker` without `sudo` or if it needs `sudo`, it needs to be password-less.
We call docker from everywhere in the codebase and one can't skip or enter the password every single time.

So my solution is to ask contributors to:
1) add their users to the sudoers
2) make `sudo` password less
This is the set up we have everywhere.

This means that we should update the documentation and not change the code.

I can help document how to improve the documentation.

Corollary: the problem is that we ignored a problem in the set-up since it was new and then this problem came back to bite us.

**Comment by sonniki** [comment]
> So my solution is to ask contributors to:
    add their users to the sudoers
    make sudo password less
    This is the set up we have everywhere.
This means that we should update the documentation and not change the code.
I can help document how to improve the documentation.

Let's do that then, only let's try to give this priority since it's blocking some interns from running Linter and other invokes that require Docker. Unfortunately, I don't have enough understanding of how this issue should be solved in the setup to be able to guide here.

**Comment by aangelo9** [comment]
I have done abit more investigating and I think that the current code does not check for Linux VM.
I have done:
```
# Add user to Docker group
sudo usermod -aG docker $USER

# Add user to sudoers
sudo visudo
# Add at the bottom $USER ALL=(ALL) NOPASSWD:ALL
```

I used this temp fix to try to access the container:
```
def docker_needs_sudo() -> bool:
    """
    Return whether Docker commands need to be run with sudo.
    """
    if os.path.exists("/.dockerenv"):
        # We're inside a Docker container — skip check
        return False
    ...
```

I found out that for Linux, the Docker daemon socket is never mounted, hence DinD check fails.
> /var/run/docker.sock:/var/run/docker.sock
```
rc = os.system("docker run hello-world 2>&1 >/dev/null")
     if rc == 0:
         return False
#
rc = os.system("sudo docker run hello-world 2>&1 >/dev/null")
    if rc == 0:
        return True
```

When in the Docker container, calling Docker will raise this error:
```
root@4ce53e2efec2:/app# docker images ls
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by gpsaggese** [comment]
Ok to put a hack to unblock, but let's clearly mark with a `TODO(gp): Remove this as per HelpersTask578`.

1) What is your set up exactly?

2) What does it mean "the current code does not check for Linux VM"?

3) Adding users to sudoers is correct. Do you know if we have those instructions in the setup? If not, we should add

4) There are two ways to run a Docker container when inside Docker: sibling and child containers.
I don't understand why `/var/run/docker.sock` is not mounted, which is required for sibling containers.

@samarth9008 and @heanhsok do you have more insights since you are Linux users?

**Comment by aangelo9** [comment]
1) Current Env Setup:
   - Windows 11 OS
   - VMWare Workstation Pro
   - Ubuntu x64 (22.04)
 Or in codebase variables:
```
WARN  hserver.py _raise_invalid_host:790                     Don't recognize host: host_os_name=Linux, am_host_os_name=None
```

2) From what I understand, [lib_tasks_docker.py](https://github.com/causify-ai/helpers/blob/master/helpers/lib_tasks_docker.py) creates the `tmp.docker-compose.yml` file that configures the Docker container. However, under `_generate_docker_compose_file()`:
```
# Taken from helpers/lib_tasks_docker.py
def _generate_docker_compose_file()
    ...
    if use_sibling_container:
        # Use sibling-container approach.
        base_app_spec["volumes"].append(
            "/var/run/docker.sock:/var/run/docker.sock"
        )
    ...
```
`use_sibling_container` is a bool variable from `hserver.use_docker_sibling_containers()`:
```
# Taken from helpers/hserver.py
def use_docker_sibling_containers() -> bool:
    """
    Return whether to use Docker sibling containers.

    Using sibling containers requires that all Docker containers in the
    same network so that they can communicate with each other.
    """
    val = is_dev4() or _is_mac_version_with_sibling_containers()
    return val
```
Where `is_dev4()` checks for interval devs, and `_is_mac_version_with_sibling_containers()` checks for mac. Hence why it does not check for Linux or if it's an external dev.

3) Current [setup](https://github.com/causify-ai/helpers/blob/master/docs/onboarding/intern.set_up_development_on_laptop.how_to_guide.md) does not ask users to add themselves to sudoers. I could update the document.

4) There are 2 approaches to this:
- This enables running basic invoke functions but does not support DinD:
```
def docker_needs_sudo() -> bool:
    """
    Return whether Docker commands need to be run with sudo.
    """
    if os.path.exists("/.dockerenv"):
        # We're inside a Docker container — skip check
        return False
```

- The other approach is to maybe place `hserver.is_external_dev()` into `hserver.use_docker_sibling_container()` as an additional condition to get `/var/run/docker.sock` mounted if DinD is absolutely necessary for interns.

**Comment by gpsaggese** [comment]
> Current [setup](https://github.com/causify-ai/helpers/blob/master/docs/onboarding/intern.set_up_development_on_laptop.how_to_guide.md) does not ask users to add themselves to sudoers. I could update the document.

Yes pls

The new approach I've been working on is about checking what functionalities are actually available in the system, rather than checking what computer is "interns" vs "mac" vs "dev" and then have a table that says "for this type of set-up, this is what we have". I'm ok with adding some hacks to keep working but they need to be clearly documented, so that we can remove them.

**Comment by aangelo9** [comment]
Understood, I will add some hacks and mark them with `TODO(gp): Remove this as per HelpersTask578` and update the setup document.

**Comment by aangelo9** [comment]
Current hack is:

- Run Docker container as root user for external linux users.
- Skip DinD for external linux users.

Problem:
- For Ubuntu, the user inside the container is "ubuntu" and does not have read or write permissions, which prevents linter from working.
- The "ubuntu" user is not in the sudoers file, and adding it requires modifying the Docker image.

**Comment by gpsaggese** [comment]
You can file an issue for this. It's a bit weird that there is a problem, since we use ubuntu on the server and everything is fine.

Maybe the ubuntu user on your user has a different id than the one on the server.
In that case, the fix is adding the id of the `ubuntu` user to our Docker containers.

@heanhsok any idea about this?

**Comment by heanhsok** [comment]
> 12:02:00 - INFO  hdbg.py init_logger:1018                               > cmd='/venv/bin/invoke print_env'
> 12:02:00 - WARN  hserver.py _raise_invalid_host:777                     Don't recognize host: host_os_name=Linux, am_host_os_name=None
> [sudo] password for ubuntu: 
> sudo: a password is required
> docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Let's rewind a bit. It looks the errors start from here.

Is this error coming from when running on host or inside the container? Could you try both? Please make sure to clear all the hacks first and use only the code from master.

- To run on host,
```bash
i print_env
```

- To run in container,
```
i docker_bash
...
/venv/bin/invoke print_env
```

If neither succeed, can you try running the following commands and share the output?
```bash
> heanhs@dev1:~/src/cmamp2$ echo $USER
heanhs
> heanhs@dev1:~/src/cmamp2$ groups $USER
heanhs : docker
> heanhs@dev1:~/src/cmamp2$ which docker
/usr/bin/docker
> heanhs@dev1:~/src/cmamp2$ ls -l /var/run/docker.sock
srw-rw---- 1 root docker 0 Apr  6 02:06 /var/run/docker.sock
```

@aangelo9

**Comment by aangelo9** [comment]
`CSFY_ENABLE_DIND` is set to 0.
```
version: '3'
services:
  base_app:
    cap_add:
      - SYS_ADMIN
    environment:
      - CSFY_ENABLE_DIND=0
      - CSFY_FORCE_TEST_FAIL=$CSFY_FORCE_TEST_FAIL
      - CSFY_HOST_NAME=alvinoangelo
      - CSFY_HOST_OS_NAME=Linux
      - CSFY_HOST_USER_NAME=alvinoangelo
      - CSFY_HOST_VERSION=6.8.0-57-generic
      - CSFY_REPO_CONFIG_CHECK=True
      - CSFY_REPO_CONFIG_PATH=
      - CSFY_AWS_ACCESS_KEY_ID=$CSFY_AWS_ACCESS_KEY_ID
      - CSFY_AWS_DEFAULT_REGION=$CSFY_AWS_DEFAULT_REGION
      - CSFY_AWS_PROFILE=$CSFY_AWS_PROFILE
      - CSFY_AWS_S3_BUCKET=$CSFY_AWS_S3_BUCKET
      - CSFY_AWS_SECRET_ACCESS_KEY=$CSFY_AWS_SECRET_ACCESS_KEY
      - CSFY_AWS_SESSION_TOKEN=$CSFY_AWS_SESSION_TOKEN
      - CSFY_ECR_BASE_PATH=$CSFY_ECR_BASE_PATH
      - CSFY_HOST_GIT_ROOT_PATH=/home/alvinoangelo/src/helpers1
      - CSFY_GIT_ROOT_PATH=/app
      - CSFY_HELPERS_ROOT_PATH=/app
      - CSFY_USE_HELPERS_AS_NESTED_MODULE=0
      - CSFY_TELEGRAM_TOKEN=$CSFY_TELEGRAM_TOKEN
      - CSFY_CI=$CSFY_CI
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GH_ACTION_ACCESS_TOKEN=$GH_ACTION_ACCESS_TOKEN
      - GH_TOKEN=$GH_ACTION_ACCESS_TOKEN
    image: ${IMAGE}
    restart: 'no'
    volumes:
      - ~/.aws:/home/.aws
      - ~/.config/gspread_pandas/:/home/.config/gspread_pandas/
      - ~/.config/gh:/home/.config/gh
      - ~/.ssh:/home/.ssh
  app:
    extends: base_app
    volumes:
      - /home/alvinoangelo/src/helpers1:/app
    working_dir: /app
  linter:
    extends: base_app
    volumes:
      - /home/alvinoangelo/src/helpers1:/src
      - ../../:/app
    working_dir: /src
    environment:
      - MYPYPATH
  jupyter_server:
    command: devops/docker_run/run_jupyter_server.sh
    environment:
      - PORT=${PORT}
    extends: app
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - ${PORT}:${PORT}
  jupyter_server_test:
    command: jupyter notebook -h 2>&1 >/dev/null
    environment:
      - PORT=${PORT}
    extends: app
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - ${PORT}:${PORT}
```
